filebeat.inputs:
  # WAF (ModSecurity) 감사 로그
  - type: log
    enabled: true
    paths:
      - /var/log/modsec/audit.log
    fields:
      service: modsecurity-waf
    multiline.pattern: '^--[a-fA-F0-9]{8}-[A-Z]--$'
    multiline.negate: true
    multiline.match: after

  # Metasploitable 2 시스템 로그
  - type: log
    enabled: true
    paths:
      - /var/log/msf/syslog
      - /var/log/msf/auth.log
      - /var/log/msf/daemon.log
    fields:
      service: metasploitable2

output.logstash:
  hosts: [ "logstash:5044" ]

# Filebeat 내부 로그 수준 설정
logging.level: info
